/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import ConManager.connection;
import Entity.UserClass;
import java.awt.Font;


/**
 *
 * @author user
 */
public class frmHome extends javax.swing.JFrame {
      frmIPatientRegistration frmregister=new frmIPatientRegistration();
       frmIPatientAppointment frmappoint=new frmIPatientAppointment();
 frmIPatientExamination frmexam=new frmIPatientExamination();
  frmIBrowse frmbrowse=new frmIBrowse();
  frmIUsers frmUser=new frmIUsers();
  Font fontDefault;
  Font fontNew;
  UserClass UserObject=new UserClass();
  //
  String[] rowresult = new String[6];
    /**
     * Creates new form frmPatient
     */
    public frmHome() {
        initComponents();
        this.add(frmregister);
       this.add(frmappoint);
       this.add(frmUser);
       this.add(frmexam);
        this.add(frmbrowse);
        frmbrowse.setLocation(this.getWidth()/6, this.getHeight()/20);
         frmexam.setLocation(this.getWidth()/6, this.getHeight()/20);
          frmappoint.setLocation(this.getWidth()/6, this.getHeight()/20);
           frmregister.setLocation(this.getWidth()/6, this.getHeight()/20);
           frmUser.setLocation(this.getWidth()/6, this.getHeight()/20);
          fontDefault=  btnPatientRegistration.getFont();
          fontNew = new Font("Arial", Font.BOLD, 14);
      
        rowresult=  UserObject.getUser(connection.strUser);
        if(rowresult[4].toString().equalsIgnoreCase("Encoder"))
              {
        btnAppointment.setEnabled(true);       
        btnUsers.setEnabled(false);
        btnPatientBrowse.setEnabled(false);
        btnPatientExamination.setEnabled(false);
         btnPatientRegistration.setEnabled(true);     
              }
        else if(rowresult[4].toString().equalsIgnoreCase("Doctor"))
              {
        btnUsers.setEnabled(false);
        btnAppointment.setEnabled(true);
        btnPatientBrowse.setEnabled(true);
        btnPatientExamination.setEnabled(true);
        btnPatientRegistration.setEnabled(false);     
              
              }
        else if (rowresult[4].toString().equalsIgnoreCase("Admin"))
              {
              
        btnAppointment.setEnabled(false);
        btnPatientBrowse.setEnabled(false);
        btnPatientExamination.setEnabled(false);
        btnPatientRegistration.setEnabled(false);
        btnUsers.setEnabled(true);      
              }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnUsers = new javax.swing.JButton();
        btnPatientRegistration = new javax.swing.JButton();
        btnPatientBrowse = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();
        btnPatientExamination = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnUsers.setText("Users");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        btnPatientRegistration.setText("Patient Registration");
        btnPatientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientRegistrationActionPerformed(evt);
            }
        });

        btnPatientBrowse.setText("Patient Browse");
        btnPatientBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientBrowseActionPerformed(evt);
            }
        });

        btnAppointment.setText("Patient Appointment");
        btnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentActionPerformed(evt);
            }
        });

        btnPatientExamination.setText("Patient Examination");
        btnPatientExamination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientExaminationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnPatientRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnPatientBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnPatientExamination, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPatientBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAppointment)
                        .addComponent(btnPatientExamination))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUsers)
                        .addComponent(btnPatientRegistration)))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(btnUsers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnPatientRegistration, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnPatientBrowse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnAppointment, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnPatientExamination, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(436, 436, 436)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientRegistrationActionPerformed
        // TODO add your handling code here:
         frmUser.setVisible(false);
        frmexam.setVisible(false);
        frmbrowse.setVisible(false);
         frmappoint.setVisible(false); 
        frmregister.setVisible(true);
        
      
        btnPatientRegistration.setFont(fontNew);
        btnUsers.setFont(fontDefault);
        btnAppointment.setFont(fontDefault);
        btnPatientBrowse.setFont(fontDefault);
        btnPatientExamination.setFont(fontDefault);
        
        
        
       
    }//GEN-LAST:event_btnPatientRegistrationActionPerformed

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
         frmUser.setVisible(false);
        frmexam.setVisible(false);
        frmregister.setVisible(false);
         frmbrowse.setVisible(false);
        frmappoint.setVisible(true);       
       
        btnPatientRegistration.setFont(fontDefault);
        btnUsers.setFont(fontDefault);
        btnAppointment.setFont(fontNew);
        btnPatientBrowse.setFont(fontDefault);
        btnPatientExamination.setFont(fontDefault);
    }//GEN-LAST:event_btnAppointmentActionPerformed

    private void btnPatientExaminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientExaminationActionPerformed
        // TODO add your handling code here:
         frmappoint.setVisible(false);
         frmregister.setVisible(false);
          frmbrowse.setVisible(false);
        frmUser.setVisible(false);
        frmexam.setVisible(true);
         btnPatientRegistration.setFont(fontDefault);
        btnUsers.setFont(fontDefault);
        btnAppointment.setFont(fontDefault);
        btnPatientBrowse.setFont(fontDefault);
        btnPatientExamination.setFont(fontNew);
    }//GEN-LAST:event_btnPatientExaminationActionPerformed

    private void btnPatientBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientBrowseActionPerformed
        // TODO add your handling code here:
          frmUser.setVisible(false);
        frmregister.setVisible(false);
         frmexam.setVisible(false);
         frmappoint.setVisible(false);
       // new frmIPatientRegistration().setVisible(true);
        frmbrowse.setVisible(true);
       btnPatientRegistration.setFont(fontDefault);
        btnUsers.setFont(fontDefault);
        btnAppointment.setFont(fontDefault);
        btnPatientBrowse.setFont(fontNew);
        btnPatientExamination.setFont(fontDefault);
    }//GEN-LAST:event_btnPatientBrowseActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
        
        frmregister.setVisible(false);
         frmexam.setVisible(false);
         frmappoint.setVisible(false);
        frmbrowse.setVisible(false);
         frmUser.setVisible(true);
        btnPatientRegistration.setFont(fontDefault);
        btnUsers.setFont(fontNew);
        btnAppointment.setFont(fontDefault);
        btnPatientBrowse.setFont(fontDefault);
        btnPatientExamination.setFont(fontDefault);
    }//GEN-LAST:event_btnUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnPatientBrowse;
    private javax.swing.JButton btnPatientExamination;
    private javax.swing.JButton btnPatientRegistration;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
