/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Forms;

import Entity.PatientExamination;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class frmIBrowse extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBrowse
     */
    DefaultTableModel model = new DefaultTableModel();
    PatientExamination objPatientExamination=new PatientExamination();
    public frmIBrowse() {
        initComponents();
        String Sql_Table="select * from patientexamination ";
         model=objPatientExamination.ReadPatientTable(Sql_Table);
         this.tbl.setModel(model);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel26 = new javax.swing.JLabel();
        txtPatient = new javax.swing.JTextField();
        frmButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel26.setText("Patient Id");

        txtPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientActionPerformed(evt);
            }
        });

        frmButton.setText("Search");
        frmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmButtonActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient_Id", "Diagnose", "Prescription", "Date", "ReferedTo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(txtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(frmButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frmButton)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        try {
            int index=tbl.getSelectedRow();
            TableModel  model1=tbl.getModel();
            String strpatientId= model1.getValueAt(index, 0).toString();
            String strDiagnose= model1.getValueAt(index, 1).toString();
            String strPrescription= model1.getValueAt(index, 2).toString();
            Date strDate= new SimpleDateFormat("yyyy-MM-dd").parse((String)model1.getValueAt(index, 3));
            String strReferedTo= model1.getValueAt(index, 4).toString();
            

            
//            txtPatientId.setText(strpatientId);
//           cmbDiagnose.setSelectedItem(strDiagnose);
//            txtPrescription.setText(strPrescription);
//            txtReferedTo.setText(strReferedTo);
//            txtDate.setDate(strDate);  
            

            // TODO add your handling code here:
        } catch (ParseException ex) {
            Logger.getLogger(frmIPatientRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMouseClicked

    private void frmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmButtonActionPerformed
        // TODO add your handling code here:
        try{ String Sql_Table="select * from patientexamination where Patient_Id = '"+txtPatient.getText()+"'";
         model=objPatientExamination.ReadPatientTable(Sql_Table);
         this.tbl.setModel(model);}
       catch (Exception ex) {
                ex.printStackTrace();
    }
    }//GEN-LAST:event_frmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton frmButton;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtPatient;
    // End of variables declaration//GEN-END:variables
}
